### PR TITLE
fix max-w autocomplete & remove unecessary directories in the content entry

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by arkatsy** [comment]
We can definitely improve the readability of the styles. 
The way styles are being handled with css variables -> tailwind config -> using them as tailwind values, only complicates things and makes it hard to think and reason about.
The shadcn's css variables don't help either. The result is a very cluttered tailwind config.

**Comment by arkatsy** [comment]
Note, styles that are not meant to override default values from tailwind like `maxWidth`, but just add an additional option, can be put inside the `extend: {}` field, so we don't mess with the auto-completion.
I already fixed the `maxWidth` in the previous commit. 
If you want we can merge this and open another PR for improving the way we define colors and styles.

**Comment by RoksolanaVeres** [comment]
Sure, thanks, I'm merging this

**Comment by arkatsy** [comment]
You can merge now

**Pull request merged**
